### ISSUE TITLE
[CI] java format check workflow 추가

### ISSUE THREAD

**Issue by qbobl5** [woohaengshi/backend#2]
# ⚙️ ISSUE
- build 시 google-java-format 형식을 검증하는 workflow 추가

# 📄 To-Do
- [x] format-check.yml 추가
- [x] 오류가 없는지 확인
- [x] 정상적으로 빌드 테스트 시 main 에 적용
