### ISSUE TITLE
[FEAT] DB 변경에 따른 수정

### ISSUE THREAD

**Issue by rlfrkdms1** [woohaengshi/backend#21]
# ⚙️ ISSUE
- 학습 과목 테이블 추가에 따른 수정

# 📄 To-Do
- [ ] 공부기록과 관련된 과목을 학습 과목 테이블에서 가져오도록 수정
- [ ] 학습 과목 엔티티 추가
- [ ] 학습 과목 init.sql에 추가
