### ISSUE TITLE
[FEAT] 공부 기록 기능 추가

### ISSUE THREAD

**Issue by rlfrkdms1** [woohaengshi/backend#4]
# ⚙️ ISSUE
공부 기록을 저장하는 기능

# 📄 To-Do
- [x] 공부 기록 최초 기록
- [x] 공부 기록 누적 기록
- [x] 검증
    - [x] 과목 존재 여부
    - [x] 시간 format
